import fs from 'node:fs';
const worker=fs.readFileSync(new URL('../src/worker.js',import.meta.url),'utf8');
const auth=fs.readFileSync(new URL('../src/auth.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const schema=fs.readFileSync(new URL('../schema.sql',import.meta.url),'utf8');
const must=(text,needle,label)=>{if(!text.includes(needle))throw new Error(`Missing ${label}: ${needle}`);};
must(worker,'/api/admin/no-go-zones','no-go admin endpoint');
must(worker,'/api/admin/holiday-calendar','holiday calendar endpoint');
must(worker,'HOLIDAY_NO_GO_ZONE','no-go holiday enforcement');
must(worker,"request.method==='DELETE'",'future delete endpoint');
must(auth,'/api/admin/holiday-calendar','calendar auth allowance');
must(schema,'holiday_no_go_zones','no-go schema');
must(html,'Holiday calendar','holiday calendar UI');
must(html,'Add No Go Zone','no-go UI');
must(html,'Delete future request','future delete UI');
must(html,'Multiple consecutive weeks must be booked separately.','consecutive week hint');
must(html,'Your upcoming approved holidays','upcoming bookings UI');
if(worker.includes('APPS_SCRIPT_BRIDGE_URL'))throw new Error('Google Calendar bridge should be removed');
if(worker.includes('createCalendar('))throw new Error('Calendar creation should be removed');
if(html.includes('Calendar sync failed'))throw new Error('Calendar sync UI should be removed');
console.log('Manager Time Off database-only smoke checks passed.');
